#Net c/s Version1.0 leizhiabc@163.com
######################################
#init compile

all : 4st
.PHONY : all
clean : 
	rm -f *.o
	rm -f *.bin
4st : 4st.c 
	gcc -w 4st.c -o 4st.bin
######################################
